CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS apontamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_usuario VARCHAR(254) NOT NULL,
    semana VARCHAR(80) NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    conteudo CLOB NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    FOREIGN KEY (email_usuario) REFERENCES usuarios(email)
);
CREATE INDEX IF NOT EXISTS idx_apontamento_usuario ON apontamento(email_usuario);

-- Atualiza tambem bancos existentes, sem alterar os registros antigos.
ALTER TABLE apontamento ADD COLUMN IF NOT EXISTS inicio_em TIMESTAMP;
ALTER TABLE apontamento ADD COLUMN IF NOT EXISTS fim_em TIMESTAMP;

